"""initial schema

Revision ID: ed525c931838
Revises: 
Create Date: 2026-05-22 18:11:42.891779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ed525c931838'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id_setting', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_setting')
    )
    op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=True)
    op.create_table('assessment_tools',
    sa.Column('id_assessment_tool', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id_assessment_tool'),
    sa.UniqueConstraint('name')
    )
    op.create_table('departments',
    sa.Column('id_department', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('faculty', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id_department')
    )
    op.create_table('disciplines',
    sa.Column('id_discipline', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id_discipline'),
    sa.UniqueConstraint('name')
    )
    op.create_table('llm_prompts',
    sa.Column('id_prompt', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section_key', sa.String(length=80), nullable=False),
    sa.Column('section_label', sa.String(length=200), nullable=False),
    sa.Column('is_structural', sa.Boolean(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('user_prompt_template', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_prompt'),
    sa.UniqueConstraint('section_key')
    )
    op.create_table('permissions',
    sa.Column('id_permission', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id_permission'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id_role', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_role'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stored_files',
    sa.Column('id_file', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('original_name', sa.String(length=300), nullable=False),
    sa.Column('mime', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('storage_uri', sa.String(length=500), nullable=False),
    sa.Column('id_uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_file')
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('id_department', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('avatar_color', sa.String(length=20), nullable=True),
    sa.Column('id_avatar_file', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['id_avatar_file'], ['stored_files.id_file'], ),
    sa.ForeignKeyConstraint(['id_department'], ['departments.id_department'], ),
    sa.ForeignKeyConstraint(['id_role'], ['roles.id_role'], ),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('login')
    )
    op.create_foreign_key('fk_stored_files_uploaded_by', 'stored_files', 'users', ['id_uploaded_by'], ['id_user'])
    op.create_table('dictionary_entries',
    sa.Column('id_entry', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=120), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('direction_code', sa.String(length=20), nullable=True),
    sa.Column('id_discipline', sa.Integer(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id_user'], ),
    sa.ForeignKeyConstraint(['id_discipline'], ['disciplines.id_discipline'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_entry')
    )
    op.create_index(op.f('ix_dictionary_entries_direction_code'), 'dictionary_entries', ['direction_code'], unique=False)
    op.create_index(op.f('ix_dictionary_entries_id_discipline'), 'dictionary_entries', ['id_discipline'], unique=False)
    op.create_index(op.f('ix_dictionary_entries_kind'), 'dictionary_entries', ['kind'], unique=False)
    op.create_index('ix_dictionary_entries_kind_value', 'dictionary_entries', ['kind', 'value'], unique=False)
    op.create_table('directions',
    sa.Column('id_direction', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('profile', sa.String(length=200), nullable=True),
    sa.Column('degree_level', sa.String(length=50), nullable=True),
    sa.Column('id_fgos_file', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_fgos_file'], ['stored_files.id_file'], ),
    sa.PrimaryKeyConstraint('id_direction')
    )
    op.create_table('notifications',
    sa.Column('id_notification', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_rpd', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_notification')
    )
    op.create_table('role_permissions',
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('id_permission', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_permission'], ['permissions.id_permission'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_role'], ['roles.id_role'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_role', 'id_permission')
    )
    op.create_table('rpd',
    sa.Column('id_rpd', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_discipline', sa.Integer(), nullable=False),
    sa.Column('id_author', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=9), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('goals_text', sa.Text(), nullable=True),
    sa.Column('tasks_text', sa.Text(), nullable=True),
    sa.Column('objects_text', sa.Text(), nullable=True),
    sa.Column('requirements_text', sa.Text(), nullable=True),
    sa.Column('educational_tech', sa.Text(), nullable=True),
    sa.Column('methodical_recommendations', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('based_on_rpd_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['based_on_rpd_id'], ['rpd.id_rpd'], ),
    sa.ForeignKeyConstraint(['id_author'], ['users.id_user'], ),
    sa.ForeignKeyConstraint(['id_discipline'], ['disciplines.id_discipline'], ),
    sa.PrimaryKeyConstraint('id_rpd')
    )
    op.create_table('approval_stages',
    sa.Column('id_approval', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_rpd', sa.Integer(), nullable=False),
    sa.Column('id_reviewer', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_reviewer'], ['users.id_user'], ),
    sa.ForeignKeyConstraint(['id_rpd'], ['rpd.id_rpd'], ),
    sa.PrimaryKeyConstraint('id_approval')
    )
    op.create_table('bups',
    sa.Column('id_bup', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_direction', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('faculty', sa.String(length=150), nullable=True),
    sa.Column('profile', sa.String(length=200), nullable=True),
    sa.Column('form_of_study', sa.String(length=40), nullable=True),
    sa.Column('id_source_file', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_direction'], ['directions.id_direction'], ),
    sa.ForeignKeyConstraint(['id_source_file'], ['stored_files.id_file'], ),
    sa.PrimaryKeyConstraint('id_bup')
    )
    op.create_table('competencies',
    sa.Column('id_competency', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_direction', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_direction'], ['directions.id_direction'], ),
    sa.PrimaryKeyConstraint('id_competency')
    )
    op.create_table('direction_programs',
    sa.Column('id_program', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_direction', sa.Integer(), nullable=False),
    sa.Column('profile', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['id_direction'], ['directions.id_direction'], ),
    sa.PrimaryKeyConstraint('id_program')
    )
    op.create_table('llm_generation_log',
    sa.Column('id_log', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_rpd', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('context_sources', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_rpd'], ['rpd.id_rpd'], ),
    sa.PrimaryKeyConstraint('id_log')
    )
    op.create_table('rpd_approval_routes',
    sa.Column('id_route', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_rpd', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.SmallInteger(), nullable=False),
    sa.Column('id_reviewer', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_reviewer'], ['users.id_user'], ),
    sa.ForeignKeyConstraint(['id_rpd'], ['rpd.id_rpd'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_route')
    )
    op.create_table('rpd_databases',
    sa.Column('id_database', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_rpd', sa.Integer(), nullable=False),
    sa.Column('db_type', sa.String(length=120), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_rpd'], ['rpd.id_rpd'], ),
    sa.PrimaryKeyConstraint('id_database')
    )
    op.create_table('rpd_developers',
    sa.Column('id_rpd_developer', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_rpd', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_rpd'], ['rpd.id_rpd'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_rpd_developer')
    )
    op.create_table('rpd_fos_files',
    sa.Column('id_rpd_fos', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_rpd', sa.Integer(), nullable=False),
    sa.Column('id_file', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_file'], ['stored_files.id_file'], ),
    sa.ForeignKeyConstraint(['id_rpd'], ['rpd.id_rpd'], ),
    sa.PrimaryKeyConstraint('id_rpd_fos')
    )
    op.create_table('rpd_literature',
    sa.Column('id_literature', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_rpd', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=120), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('copies_count', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('availability', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('authors', sa.String(length=500), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id_rpd'], ['rpd.id_rpd'], ),
    sa.PrimaryKeyConstraint('id_literature')
    )
    op.create_table('rpd_material_tech',
    sa.Column('id_material_tech', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_rpd', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=100), nullable=False),
    sa.Column('equipment', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_rpd'], ['rpd.id_rpd'], ),
    sa.PrimaryKeyConstraint('id_material_tech')
    )
    op.create_table('rpd_sections',
    sa.Column('id_section', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_rpd', sa.Integer(), nullable=False),
    sa.Column('section_number', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('brief_content', sa.Text(), nullable=True),
    sa.Column('lecture_hours', sa.Integer(), nullable=True),
    sa.Column('practice_hours', sa.Integer(), nullable=True),
    sa.Column('lab_hours', sa.Integer(), nullable=True),
    sa.Column('self_study_hours', sa.Integer(), nullable=True),
    sa.Column('semester', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_rpd'], ['rpd.id_rpd'], ),
    sa.PrimaryKeyConstraint('id_section')
    )
    op.create_table('rpd_software',
    sa.Column('id_software', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_rpd', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('license_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_rpd'], ['rpd.id_rpd'], ),
    sa.PrimaryKeyConstraint('id_software')
    )
    op.create_table('rpd_topics',
    sa.Column('id_topic', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_rpd', sa.Integer(), nullable=False),
    sa.Column('topic_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_rpd'], ['rpd.id_rpd'], ),
    sa.PrimaryKeyConstraint('id_topic')
    )
    op.create_table('uploaded_documents',
    sa.Column('id_document', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_rpd', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_rpd'], ['rpd.id_rpd'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_document')
    )
    op.create_table('bup_disciplines',
    sa.Column('id_bup_discipline', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_bup', sa.Integer(), nullable=False),
    sa.Column('id_discipline', sa.Integer(), nullable=False),
    sa.Column('id_department', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('semester', sa.String(length=100), nullable=True),
    sa.Column('control_form', sa.String(length=255), nullable=True),
    sa.Column('total_hours', sa.Integer(), nullable=True),
    sa.Column('exam_hours', sa.Integer(), nullable=True),
    sa.Column('lecture_hours', sa.Integer(), nullable=True),
    sa.Column('lab_hours', sa.Integer(), nullable=True),
    sa.Column('practice_hours', sa.Integer(), nullable=True),
    sa.Column('ksr_hours', sa.Integer(), nullable=True),
    sa.Column('self_study_hours', sa.Integer(), nullable=True),
    sa.Column('zet', sa.Integer(), nullable=True),
    sa.Column('semesters_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['id_bup'], ['bups.id_bup'], ),
    sa.ForeignKeyConstraint(['id_department'], ['departments.id_department'], ),
    sa.ForeignKeyConstraint(['id_discipline'], ['disciplines.id_discipline'], ),
    sa.PrimaryKeyConstraint('id_bup_discipline')
    )
    op.create_table('competency_indicators',
    sa.Column('id_indicator', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_competency', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_competency'], ['competencies.id_competency'], ),
    sa.PrimaryKeyConstraint('id_indicator')
    )
    op.create_table('uploaded_document_sections',
    sa.Column('id_section_chunk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_document', sa.Integer(), nullable=False),
    sa.Column('section_key', sa.String(length=80), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('extraction_method', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_document'], ['uploaded_documents.id_document'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_section_chunk')
    )
    op.create_index(op.f('ix_uploaded_document_sections_section_key'), 'uploaded_document_sections', ['section_key'], unique=False)
    op.create_table('bup_discipline_competencies',
    sa.Column('id_bup_discipline_competency', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_bup_discipline', sa.Integer(), nullable=False),
    sa.Column('id_competency', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_bup_discipline'], ['bup_disciplines.id_bup_discipline'], ),
    sa.ForeignKeyConstraint(['id_competency'], ['competencies.id_competency'], ),
    sa.PrimaryKeyConstraint('id_bup_discipline_competency'),
    sa.UniqueConstraint('id_bup_discipline', 'id_competency', name='uq_bup_disc_comp')
    )
    op.create_table('rpd_bup_disciplines',
    sa.Column('id_rpd_bup_discipline', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_rpd', sa.Integer(), nullable=False),
    sa.Column('id_bup_discipline', sa.Integer(), nullable=True),
    sa.Column('bup_name', sa.String(length=300), nullable=True),
    sa.Column('bup_year', sa.Integer(), nullable=True),
    sa.Column('bup_profile', sa.String(length=200), nullable=True),
    sa.Column('direction_code', sa.String(length=20), nullable=True),
    sa.Column('direction_name', sa.String(length=200), nullable=True),
    sa.Column('direction_profile', sa.String(length=200), nullable=True),
    sa.Column('fgos_file_id', sa.Integer(), nullable=True),
    sa.Column('fgos_file_name', sa.String(length=300), nullable=True),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('semester', sa.String(length=100), nullable=True),
    sa.Column('control_form', sa.String(length=255), nullable=True),
    sa.Column('total_hours', sa.Integer(), nullable=True),
    sa.Column('exam_hours', sa.Integer(), nullable=True),
    sa.Column('lecture_hours', sa.Integer(), nullable=True),
    sa.Column('lab_hours', sa.Integer(), nullable=True),
    sa.Column('practice_hours', sa.Integer(), nullable=True),
    sa.Column('ksr_hours', sa.Integer(), nullable=True),
    sa.Column('self_study_hours', sa.Integer(), nullable=True),
    sa.Column('zet', sa.Integer(), nullable=True),
    sa.Column('semesters_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('discipline_name', sa.String(length=200), nullable=True),
    sa.Column('form_of_study', sa.String(length=40), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_bup_discipline'], ['bup_disciplines.id_bup_discipline'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_rpd'], ['rpd.id_rpd'], ),
    sa.PrimaryKeyConstraint('id_rpd_bup_discipline'),
    sa.UniqueConstraint('id_rpd', 'id_bup_discipline', name='uq_rpd_bup_disc')
    )
    op.create_table('rpd_learning_outcomes',
    sa.Column('id_outcome', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_rpd', sa.Integer(), nullable=False),
    sa.Column('id_indicator', sa.Integer(), nullable=True),
    sa.Column('outcome_text', sa.Text(), nullable=True),
    sa.Column('assessment_tool', sa.String(length=200), nullable=True),
    sa.Column('indicator_code', sa.String(length=20), nullable=True),
    sa.Column('indicator_description', sa.Text(), nullable=True),
    sa.Column('competency_code', sa.String(length=20), nullable=True),
    sa.Column('competency_name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_indicator'], ['competency_indicators.id_indicator'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_rpd'], ['rpd.id_rpd'], ),
    sa.PrimaryKeyConstraint('id_outcome')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_stored_files_uploaded_by', 'stored_files', type_='foreignkey')
    op.drop_table('rpd_learning_outcomes')
    op.drop_table('rpd_bup_disciplines')
    op.drop_table('bup_discipline_competencies')
    op.drop_index(op.f('ix_uploaded_document_sections_section_key'), table_name='uploaded_document_sections')
    op.drop_table('uploaded_document_sections')
    op.drop_table('competency_indicators')
    op.drop_table('bup_disciplines')
    op.drop_table('uploaded_documents')
    op.drop_table('rpd_topics')
    op.drop_table('rpd_software')
    op.drop_table('rpd_sections')
    op.drop_table('rpd_material_tech')
    op.drop_table('rpd_literature')
    op.drop_table('rpd_fos_files')
    op.drop_table('rpd_developers')
    op.drop_table('rpd_databases')
    op.drop_table('rpd_approval_routes')
    op.drop_table('llm_generation_log')
    op.drop_table('direction_programs')
    op.drop_table('competencies')
    op.drop_table('bups')
    op.drop_table('approval_stages')
    op.drop_table('rpd')
    op.drop_table('role_permissions')
    op.drop_table('notifications')
    op.drop_table('directions')
    op.drop_index('ix_dictionary_entries_kind_value', table_name='dictionary_entries')
    op.drop_index(op.f('ix_dictionary_entries_kind'), table_name='dictionary_entries')
    op.drop_index(op.f('ix_dictionary_entries_id_discipline'), table_name='dictionary_entries')
    op.drop_index(op.f('ix_dictionary_entries_direction_code'), table_name='dictionary_entries')
    op.drop_table('dictionary_entries')
    op.drop_table('users')
    op.drop_table('stored_files')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('llm_prompts')
    op.drop_table('disciplines')
    op.drop_table('departments')
    op.drop_table('assessment_tools')
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
